services:
  dagster-code:
    image: 368355641188.dkr.ecr.ap-south-1.amazonaws.com/rahulk-dagster:latest
    container_name: dagster-code
    environment:
      DAGSTER_HOME: /opt/dagster/dagster_home
    volumes:
      - dagster_home:/opt/dagster/dagster_home
    expose:
      - "4000"

  dagster-webserver:
    image: 368355641188.dkr.ecr.ap-south-1.amazonaws.com/rahulk-dagster:latest
    container_name: dagster-webserver
    environment:
      DAGSTER_HOME: /opt/dagster/dagster_home
    volumes:
      - dagster_home:/opt/dagster/dagster_home
    ports:
      - "3000:3000"
    depends_on:
      - dagster-code
    command:
      - dagster-webserver
      - -h
      - 0.0.0.0
      - -p
      - "3000"
      - -w
      - /opt/dagster/app/workspace.yaml

  dagster-daemon:
    image: 368355641188.dkr.ecr.ap-south-1.amazonaws.com/rahulk-dagster:latest
    container_name: dagster-daemon
    environment:
      DAGSTER_HOME: /opt/dagster/dagster_home
    volumes:
      - dagster_home:/opt/dagster/dagster_home
    depends_on:
      - dagster-code
    command:
      - dagster-daemon
      - run
      
volumes:
  dagster_home: